name: CI/CD

on: [push]

jobs:
  stubs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U mypy
    - name: Stubgen Run
      run: stubgen rpd/data/__init__.py rpd/factories/__init__.py rpd/internal/__init__.py rpd/ext/__init__.py rpd/__init__.py -o .
  lint:
    needs: [stubs]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U flynt black pip install isort[requirements_deprecated_finder]
    - name: Isort
      run: isort . --profile black --check
    - name: Black
      run: black . --check